### ISSUE TITLE
Boxes above plot when knitting?

### ISSUE THREAD

**Issue by 7yl4r** [mandykarnauskas/GoM-Ecosystem-Status-Report#1]
When knitting with the plotIndiciatorTimeSeries function a table is injected above the figure. 

![image](https://user-images.githubusercontent.com/1051390/74179784-1d1d4f00-4c0c-11ea-854c-aee5636cd194.png)

I am guessing this has something to do with the figure layout.
Any guidance on how to remove the boxes would be much appreciated.

**Comment by MandyKarnauskas-NOAA** [comment]
Issue fixed with commit 914f18c
